name: run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      PYTHONIOENCODING: utf-8
      # ↓ 필요한 비밀값들 (레포 Secrets에 이미 저장되어 있어야 합니다)
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      # 선택: 일본어→한국어 번역 사용 시 1, 미사용 0
      SLACK_TRANSLATE_JA2KO: ${{ secrets.SLACK_TRANSLATE_JA2KO }}
      # HTTP 파싱이 0건일 때를 대비해 기본값으로 브라우저 수집 강제
      FORCE_PLAYWRIGHT: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.46.0
          pip install beautifulsoup4 lxml requests
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run python app.py
        run: |
          python app.py

      - name: Upload CSV artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: csv-${{ github.run_id }}
          path: data/*.csv
          if-no-files-found: warn
          compression-level: 6

      - name: Upload debug files (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.run_id }}
          path: data/debug/**
          if-no-files-found: warn
          compression-level: 6
