name: Qoo10 JP Beauty Ranking

on:
  workflow_dispatch: {}
  schedule:
    - cron: "10 0 * * *"   # 매일 09:10 KST (UTC 00:10)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas beautifulsoup4 lxml pytz \
                     google-api-python-client google-auth google-auth-oauthlib playwright
          python -m playwright install --with-deps chromium

      - name: Run
        run: python app.py

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csv-${{ github.run_id }}
          path: |
            data/*.csv
            data/debug/*
