name: qoo10jp-beauty-rank

on:
  workflow_dispatch:
  # 필요하면 주기에 맞춰 켜세요 (예: 매일 09:10 KST = 00:10 UTC)
  # schedule:
  #   - cron: '10 3 * * *'

concurrency:
  group: qoo10jp-beauty-rank
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      TZ: Asia/Seoul
      PYTHONUNBUFFERED: "1"
      PYTHONIOENCODING: "utf-8"
      # 동작 옵션
      QOO10_MAX_RANK: "200"           # 100/200 등으로 조절 가능
      SLACK_TRANSLATE_JA2KO: "1"      # 일본어만 한국어로 1줄 번역 (비활성화: 0)

      # 시크릿(필수)
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.46.0
          pip install beautifulsoup4 lxml requests pandas
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2
          # 번역 백엔드(둘 중 하나라도 성공하도록 둘 다 설치)
          pip install googletrans==4.0.0rc1 deep-translator

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run python app.py
        run: |
          echo "[INFO] 수집 시작"
          python app.py

      - name: Upload CSV artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csv-${{ github.run_id }}
          path: data/*.csv
          if-no-files-found: warn
          compression-level: 6

      - name: Upload debug files (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.run_id }}
          path: data/debug/**
          if-no-files-found: warn
          compression-level: 6
