name: Qoo10 JP Beauty Ranking

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"   # KST 13:00

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      SLACK_TRANSLATE_JA2KO: ${{ secrets.SLACK_TRANSLATE_JA2KO }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ⬇️ Playwright 브라우저 & 시스템 의존성 설치 (필수)
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run python app.py
        run: |
          python app.py

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csv-${{ github.run_id }}
          path: data/*.csv
          if-no-files-found: warn
          include-hidden-files: false
